// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9dVUoFhqeqbAzsQFT2GtCryipgltqvWg',
    appId: '1:496883902884:web:708ead15d1a74753a13931',
    messagingSenderId: '496883902884',
    projectId: 'safarmarketplace-3ae69',
    authDomain: 'safarmarketplace-3ae69.firebaseapp.com',
    storageBucket: 'safarmarketplace-3ae69.firebasestorage.app',
    measurementId: 'G-HEQC2STEVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-eY4soNrJoLVIZyIqKn9TUL8jar_Q-k4',
    appId: '1:496883902884:android:b867b37baff0705ba13931',
    messagingSenderId: '496883902884',
    projectId: 'safarmarketplace-3ae69',
    storageBucket: 'safarmarketplace-3ae69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDtLbfhkHd89ThqpyQeUrra07QOAdOl8',
    appId: '1:496883902884:ios:57931cfbc28a5816a13931',
    messagingSenderId: '496883902884',
    projectId: 'safarmarketplace-3ae69',
    storageBucket: 'safarmarketplace-3ae69.firebasestorage.app',
    androidClientId: '496883902884-9tb9ctg9qd2d91rmotkj6jeo15e5t2l0.apps.googleusercontent.com',
    iosClientId: '496883902884-81t8ljupskgfpchhsjhkfhjkk3avr03i.apps.googleusercontent.com',
    iosBundleId: 'com.example.safarStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQDtLbfhkHd89ThqpyQeUrra07QOAdOl8',
    appId: '1:496883902884:ios:57931cfbc28a5816a13931',
    messagingSenderId: '496883902884',
    projectId: 'safarmarketplace-3ae69',
    storageBucket: 'safarmarketplace-3ae69.firebasestorage.app',
    iosBundleId: 'com.example.safarStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9dVUoFhqeqbAzsQFT2GtCryipgltqvWg',
    appId: '1:496883902884:web:a859ef643927fa73a13931',
    messagingSenderId: '496883902884',
    projectId: 'safarmarketplace-3ae69',
    authDomain: 'safarmarketplace-3ae69.firebaseapp.com',
    storageBucket: 'safarmarketplace-3ae69.firebasestorage.app',
    measurementId: 'G-MJLF1W7EPM',
  );
}